CREATE TABLE `posts` (
	`id` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_bin',
	`caption` LONGTEXT NULL COLLATE 'utf8mb4_bin',
	`picture_url` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_bin',
	`pos` DOUBLE NULL DEFAULT NULL,
	`neu` DOUBLE NULL DEFAULT NULL,
	`neg` DOUBLE NULL DEFAULT NULL,
	`hashtag` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_bin',
	UNIQUE INDEX `id` (`id`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;
